GRANT CONNECT, TEMP ON DATABASE initdb TO initest;
GRANT USAGE ON SCHEMA initest TO initest;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA initest TO initest;
GRANT ALL ON ALL SEQUENCES IN SCHEMA  initest TO initest;